var clock = new Clock();
var item = location.hash.replace('#', '');
item = decodeURIComponent(item);
$('#domain').html(item);
var items = JSON.parse(item);
var day = formatTimeDelta(clock.getSumToday(items));
var week = formatTimeDelta(clock.getSumThisWeek(items));
var month = formatTimeDelta(clock.getSumThisMonth(items));
$('#day').html("今天: "+day);
$('#week').html("本周: "+week);
$('#month').html("本月: "+month);
$('#saying').html(getSaying());